# Generated by Django 5.1.1 on 2026-03-19 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPerformance',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_attempts', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0)),
                ('avg_weighted_score', models.FloatField(default=0)),
                ('best_score', models.FloatField(default=0)),
                ('elo_points', models.IntegerField(default=1000)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
