# Generated by Django 5.1.1 on 2026-03-19 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperformance',
            name='avg_weighted_score',
        ),
        migrations.CreateModel(
            name='TopicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('total_attempts', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0)),
                ('best_score', models.FloatField(default=0)),
                ('elo_points', models.IntegerField(default=1000)),
                ('rank', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['topic', '-elo_points'], name='analytics_t_topic_59759b_idx')],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
